### PR TITLE
fix(libsql-sys): fix non-Unix compilation when rusqlite feature is disabled

### PR DESCRIPTION
**Pull request by ns-ylambert**
This commit fixes a compilation error introduced in commit 8ea257afe9534e58cf90c5ee8ccad4fc7545d416 on non-Unix systems.

### CODE REVIEW

**Comment by ns-ylambert** [comment]
https://github.com/tursodatabase/libsql/pull/2048

**Comment by ns-ylambert** [comment]
This PR fixes issue #2049.

**Comment by AdrianEddy** [comment]
any update on this? It's a simple fix and the build is clearly broken. Is there anything holding this back?

**Comment by songday** [comment]
> any update on this? It's a simple fix and the build is clearly broken. Is there anything holding this back?

Currently, they seem focusing on their new project: `Turso` (former Limbo)
this might take a while to merge into the main branch

I'm migrating to `Turso` now, although it's not for production yet
